In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr1.shape

(5,)

In [8]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([       # 2D array
    [1,2,3,4,5],
    [7,8,9,0,1]
])
arr2.shape

(2, 5)

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Numpy vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# element wise operation
print("Addition:",arr1+arr2)
print("Substraction",arr1-arr2)
print("Multiplication",arr1*arr2)
print("Division",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [21]:
## Universal functions
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
print(np.log(np.e))
print(np.log10(10))

1.0
1.0


In [25]:
## Slicing and indexing

arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(arr[0][0])
print(arr[0,0])
print(arr[0][2])

1
1
3


In [31]:
for i in range(0,arr.shape[0]):
    for j in range(0,arr.shape[1]):
        if arr[i][j]==10:
            print(f"{arr[i][j]} is at row:{i} and column:{j}")

10 is at row:2 and column:1


In [35]:
# To extract 7,8,11,12 and 3 4 7 8
print(arr[1:,2:])
print(arr[:2,2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [ ]:
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data  i.e. converting data such that mean=0 and std_dev=1
normalized=(data - mean)/std_dev
print("Normalized data: ",normalized)


Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

print("Mean:",np.mean(data))
print("Median:",np.median(data))
print("Standard deviation:",np.std(data))
print("Variance:",np.var(data))

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [42]:
# Logical operations
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
print(data[data>5])
print(data[(data>=5) & (data<9)])

[ 6  7  8  9 10]
[5 6 7 8]
